https://www.tableau.com/zh-tw/downloads/public/pc64
-> https://downloads.tableau.com/public/TableauPublicDesktop-64bit-2025-2-4.exe
# TableauPublicDesktop-64bit-2025-2-4\AttachedContainer\SourceDir\Tableau\Tableau Public 2025.2
# C:\Users\Administrator\Downloads\TableauPublicDesktop\AttachedContainer\tableau-setup-pub-tableau-2025-2.25.1003.1601-x64.msi
# C:\Users\Administrator\Downloads\TableauPublicDesktop\AttachedContainer\vcredist2022_x64.exe
